# Generated by Django 5.0.6 on 2024-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='upload_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='upload_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
