# Generated by Django 5.0.6 on 2024-06-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chunk_text_alter_task_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='upload_end_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='upload_start_at',
        ),
    ]
