# Generated by Django 5.0.6 on 2024-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_upload_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
