# Generated by Django 5.0.6 on 2024-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_stats_alter_task_status_delete_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
